// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsOpXjEafB410oDJz6oF75imow4_9LaPg',
    appId: '1:793053875001:web:9d3bf24c0957b08bf1f6e8',
    messagingSenderId: '793053875001',
    projectId: 'temis-special-snacks-bd974',
    authDomain: 'temis-special-snacks-bd974.firebaseapp.com',
    storageBucket: 'temis-special-snacks-bd974.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk_pigPZeWSmX7p7KdmNIb5c3QelK3xMw',
    appId: '1:793053875001:android:757da62acd5deaaaf1f6e8',
    messagingSenderId: '793053875001',
    projectId: 'temis-special-snacks-bd974',
    storageBucket: 'temis-special-snacks-bd974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5jP40N_dm5f47pDX4_r6mBeiTIa3iIks',
    appId: '1:793053875001:ios:802a76c5fec815d0f1f6e8',
    messagingSenderId: '793053875001',
    projectId: 'temis-special-snacks-bd974',
    storageBucket: 'temis-special-snacks-bd974.appspot.com',
    iosClientId: '793053875001-am7g7a7mnb0ojlh2s58u01a4ricj7joh.apps.googleusercontent.com',
    iosBundleId: 'com.example.temisSpecialSnacks',
  );
}
